import Footer from "@/components/footer/footer";
import { Separator } from "@/components/ui/separator.component";

const TermsOfUse = () => {
  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto px-4 py-8 max-w-4xl  mt-32">
        <div className="prose prose-sm max-w-none">
          <h1 className="text-4xl font-bold mb-8 text-foreground">
            General Terms of Use
          </h1>

          <div className="space-y-6 text-foreground/90 leading-relaxed">
            <p>
              These Terms of Use (&quot;Agreement&quot;) govern your use of
              Conductor.ng mobile applications, websites, products, services,
              content, facilities, and platform (collectively, the
              &quot;Platform&quot;).
            </p>

            <p>
              This Agreement is a contract between Conductor.ng Limited having
              its registered office at …………………… and You (this term shall include
              all variations including &quot;Your&quot; and &quot;Yours&quot;)
              and governs Your use of the Platform.
            </p>

            <p>
              By accessing or using the Platform, you acknowledge that you
              accept all the terms and conditions contained in this Agreement.
              You should read all these terms carefully. You agree that this
              Agreement shall form a binding legal contract between you and
              Conductor.ng and shall include the additional terms and conditions
              and policies as may be referenced herein.
            </p>

            <p>
              This document is an electronic document in terms of Evidence Act
              2011 and rules thereunder as applicable and the provisions
              pertaining to electronic document in various statutes. This
              electronic document is generated by a computer system and does not
              require any physical or digital signatures. Please ensure that You
              read and understand all the terms under this Agreement before you
              use the Platform. If You do not wish to accept any of the terms
              under this Agreement, then please do not use the Platform or avail
              any of the Services being provided therein.
            </p>

            <p>
              Conductor.ng may amend the terms under this Agreement from
              periodically. Amendments will be effective upon Conductor.ng
              posting of such updated terms on the platform or the amended
              policies or supplemental terms on the applicable Service. Your
              continued access or use of the Platform and/or Services after such
              posting constitutes your consent to be bound by the updated terms,
              as amended.
            </p>

            <p>
              We may immediately terminate this agreement with respect to you,
              or generally cease offering or deny access to the platform or any
              portion thereof, at any time for any reason. Supplemental terms
              may apply to a particular category within the Conductor.ng
              Platform such as policies for a particular event, activity or
              promotion, and such supplemental terms will be disclosed to you.
            </p>

            <Separator className="my-8" />

            <section>
              <h2 className="text-2xl font-semibold mb-4">
                1. Independence for Drivers and Choices for Passengers
              </h2>

              <h3 className="text-xl font-medium mb-3">Our Business Model</h3>

              <div className="space-y-4">
                <p>
                  <strong>1.1.</strong> Conductor.ng is an innovative
                  car-sharing platform that serves as a bridge between car
                  owners and passengers, fostering a collaborative journey
                  experience focused on cost-effectiveness, convenience, and
                  sustainability for all involved. By connecting individuals in
                  need of transportation with available car owners, Conductor.ng
                  is revolutionizing daily commutes, offering a sustainable
                  solution that prioritizes shared mobility and redefines the
                  traditional approach to commuting.
                </p>

                <p>
                  <strong>1.2.</strong> The Passenger is free to choose the
                  Driver from the list of Drivers who indicated their interest
                  in accepting the ride schedule/request initiated by the
                  Passenger. When a Passenger chooses a Driver to provide the
                  transportation services they enter into a separate agreement
                  with Conductor.ng. The terms of the same are decided by the
                  users and Conductor.ng
                </p>

                <p>
                  <strong>1.3.</strong> The Passenger must pay directly to
                  Conductor.ng via the platform. The agreed price includes all
                  taxes associated with the ride but is not inclusive of any
                  tolls, state entry tax, parking fees or other similar
                  additional charges. Such additional charges for the ride shall
                  be borne by the Passenger/Driver. Conductor.ng will determine
                  the payable fee for each schedule on the platform, based on
                  distance and other relevant factors.
                </p>
              </div>

              <h3 className="text-xl font-medium mb-3 mt-6">
                Conductor.ng status
              </h3>

              <div className="space-y-4">
                <p>
                  <strong>1.4.</strong> Conductor.ng is a technology company
                  that does not provide transportation, logistics, courier or
                  any related services but provides a technology platform
                  through its App that enables users of the platform to arrange
                  and schedule transportation services using the platform. Each
                  Driver i.e independent third-party contractor provides the
                  transportation or related services (&quot;Services&quot;).
                </p>

                <p>
                  <strong>1.5.</strong> The Services are provided by independent
                  Drivers registered with Conductor.ng. The drivers have the
                  right to make a decision to accept or not, the schedule order
                  of a passenger. The passenger also has the right to choose the
                  driver to commute with from the options provided.
                </p>

                <p>
                  <strong>1.6.</strong> Conductor.ng will reasonably keep the
                  Platform and its contents correct and up to date but does not
                  guarantee that (the contents of) the Platform is free of
                  errors, defects, malware and viruses or that the Platform is
                  correct, up to date and accurate.
                </p>
              </div>

              <h3 className="text-xl font-medium mb-3 mt-6">
                Fees and Payments
              </h3>
              <h3 className="text-xl font-medium mb-3 mt-6">
                Payment terms applicable
              </h3>

              <div className="space-y-4">
                <p>
                  <strong>1.7.</strong> After successful completion of your
                  account registration as a Driver to use the Platform, you will
                  be required to supply your account details in which payments
                  on successful schedule and use will be paid into. You also
                  give Conductor.ng the right to retain this information.
                </p>

                <p>
                  <strong>1.8.</strong> Each User of the Platform shall have a
                  wallet account on the Platform. The funds in the user Wallet
                  Account can be used by the passenger to schedule a ride using
                  our Platform. In the event there are any funds stored in Your
                  Wallet Account including the minimum balance amount, You agree
                  and acknowledge that no interest shall accrue on such balance
                  kept in your Wallet Account.
                </p>
              </div>

              <h3 className="text-xl font-medium mb-3 mt-6">
                Refund/Rescheduling
              </h3>

              <div className="space-y-4">
                <p>
                  <strong>1.9.</strong> Passengers shall be eligible for a
                  refund of the booking fee or rescheduling if a ride is
                  cancelled due to the following events:
                </p>
                <ul className="list-disc ml-6 space-y-1">
                  <li>
                    if the driver did not show up. (refund or rescheduling)
                  </li>
                  <li>other occurrences. (rescheduling)</li>
                  <li>
                    IF PASSENGER CANCELS A RIDE 48? HOURS BEFORE THE SCHEDULED
                    TRIP
                  </li>
                </ul>

                <p>
                  <strong>1.10.</strong> Conductor.ng shall refund the amount of
                  the booking fee deducted by Conductor.ng from the user&apos;s
                  Wallet Account. Each booking fee will be refunded into the
                  user&apos;s wallet separately within thirty (30) days after
                  the request for refund was lodged on the platform.
                </p>

                <p>
                  <strong>1.11.</strong> Taxes associated with the Services
                  through the use of the Platform shall form part of the payable
                  fee and shall be paid directly to Conductor.ng using the
                  platform. Conductor.ng will not be held accountable in
                  relation to any money transactions between Passengers and
                  Drivers.
                </p>

                <p>
                  <strong>1.12.</strong> Conductor.ng, at its sole discretion,
                  may, from time to time, make available promotions, discounts,
                  referral programs and loyalty programs (hereinafter - Offers)
                  with different features to any Passenger. Such Offers may
                  affect or be applied towards service payments or ride&apos;s
                  price, reducing said amounts, and are made in bonuses.
                </p>

                <p>
                  <strong>1.13.</strong> Bonuses are valid only for use in the
                  Conductor.ng app. They are not transferable or redeemable for
                  cash. Bonuses can be used to pay for the booking fee on the
                  platform.
                </p>

                <p>
                  <strong>1.14.</strong> More information regarding Offers may
                  be provided in a notice inside the app or by any other means
                  of communication mentioned in this Agreement. Conductor.ng
                  also reserves the right to withhold or deduct Bonuses or other
                  benefits obtained through Offers in the event that
                  Conductor.ng determines or believes that the redemption of the
                  Offer or receipt of the Bonuses was in error, fraudulent,
                  illegal, or in violation of the applicable promotion or these
                  Terms. Conductor.ng reserves the right to terminate,
                  discontinue, modify or cancel any Offers at any time and in
                  its sole discretion without notice to the user.
                </p>
              </div>
            </section>

            <Separator className="my-8" />

            <section>
              <h2 className="text-2xl font-semibold mb-4">
                2. Your Conductor.ng Account
              </h2>

              <h3 className="text-xl font-medium mb-3">Account registration</h3>

              <div className="space-y-4">
                <p>
                  <strong>2.1.</strong> To access the functionality of the
                  Platform, drivers and passengers must create an account with
                  us. In order to create and maintain your Conductor.ng account
                  with us, You represent and warrant that You:
                </p>
                <ol className="list-decimal ml-6 space-y-1">
                  <li>are at least 18 years of age;</li>
                  <li>
                    have the legal capacity to enter into a legally binding
                    agreement under the applicable law of Nigeria;
                  </li>
                  <li>
                    shall ensure that Your device meets all technical and
                    operational specifications required to the use of the
                    Platform. These specifications are subject to change from
                    time to time. The use and performance of the Platform may be
                    affected by these factors. Ensuring compatibility with these
                    specifications is solely Your responsibility.
                  </li>
                </ol>

                <p>
                  <strong>2.2.</strong> In order to create and use a
                  Conductor.ng Account, you shall have to register Your account
                  with us. For opening an account and in order to prevent fraud,
                  to ensure your security and comply with anti-money laundering,
                  sanctions laws and regulations (as applicable), we will ask
                  for Your name, email address, postal address, date of birth,
                  at least one valid payment method, and/or any other
                  information that will allow us to identify you. You agree that
                  you will provide accurate and up-to-date information about
                  yourself and you authorize us to take whatever actions we deem
                  necessary to verify the accuracy of any information submitted
                  in conjunction with your account. You also agree to provide us
                  with reasonable assistance in verifying such information upon
                  our request.
                </p>

                <p>
                  <strong>2.3.</strong> Conductor.ng shall bear no liability for
                  false, incomplete, old or incorrect information and/or data
                  provided by you while opening your account.
                </p>

                <p>
                  <strong>2.4.</strong> Any instructions transmitted to us
                  and/or any other third-party entities from Your account, shall
                  have full legal effect, and you may not invoke the lack of
                  signature of any document as a way to exclude your
                  responsibility for the obligations assumed according to the
                  validly transmitted and executed instructions
                </p>

                <p>
                  <strong>2.5.</strong> You are solely responsible for
                  maintaining the confidentiality of Your account and any
                  information submitted by you. Your account cannot be
                  transferred, assigned or sold to a third party. We shall not
                  be liable for any loss that You may incur as a result of
                  someone else using Your password or account, either with or
                  without your knowledge.
                </p>

                <p>
                  <strong>2.6.</strong> We offer different types of accounts
                  depending on whether you use the Platform as a Passenger or as
                  a Driver. To create a driver account, You must provide us with
                  additional information, data pertaining to your eligibility as
                  a driver, Vehicle requirements and pass the verification
                  process.
                </p>

                <p>
                  <strong>2.7.</strong> We reserve the right to suspend or
                  terminate your account with immediate effect and for an
                  indefinite period, if there is reasonable cause to believe
                  that any information and/or data provided by you is incorrect
                  or false, or that the security of Your account has been
                  compromised in any way, or for any other reason
                </p>

                <p>
                  <strong>2.8.</strong> You agree to comply with all applicable
                  and relevant laws when providing/using the services and the
                  Platform, and you shall only use the Platform for lawful
                  purposes. You will not, in your use of the Platform, cause
                  nuisance, annoyance, inconvenience, or property damage. In
                  certain instances, you may be asked to provide proof of
                  identity to access or use the Platform, wherein you agree that
                  you may be denied access to or use of the Platform if you fail
                  or refuse to provide proof of identity.
                </p>

                <p>
                  <strong>2.9.</strong> We allow you to open only one account in
                  association with registration information provided by you. In
                  case of any unauthorized use of your account please
                  immediately reach us at{" "}
                  <a href="mailto:admin@conductor.ng">admin@conductor.ng</a>.
                </p>

                <p>
                  <strong>2.10.</strong> You may not authorise third parties to
                  use your account, and you may not allow persons under the age
                  of 18 to receive transportation or logistics services from
                  drivers unless they are accompanied by you. You may not assign
                  or otherwise transfer Your account to any other person or
                  entity.
                </p>

                <p>
                  <strong>2.12.</strong> You are responsible for obtaining the
                  data network access necessary to use the Platform. Your mobile
                  network&apos;s data and messaging rates and fees may apply if
                  you access or use the Platform from a wireless-enabled device
                  and you shall be responsible for such rates and fees. You are
                  responsible for acquiring and updating compatible hardware or
                  devices necessary to access and use the Platform and any
                  updates thereto. Conductor.ng does not guarantee that the
                  Platform, or any portion thereof, will function on any
                  particular hardware or devices. In addition, the Platform may
                  be subject to malfunctions and delays inherent in the use of
                  the Internet and electronic communications.
                </p>
              </div>

              <h3 className="text-xl font-medium mb-3 mt-6">
                Maintaining your account
              </h3>

              <div className="space-y-4">
                <p>
                  <strong>2.13.</strong> You must promptly update your details
                  if they change. If your mobile number changes, notify us as
                  soon as possible. If you no longer use Your number, Your
                  mobile operator may issue it to a new person who, when using
                  the Platform, may access Your account.
                </p>

                <p>
                  <strong>2.14.</strong> You may not authorise others to use
                  your account. You must maintain security of access to Your
                  device and secrecy of Your login information. You will be
                  responsible for all activity that occurs under Your account.
                  If You suspect that your account has been compromised by a
                  third party, please let us know by contacting{" "}
                  <a href="mailto:admin@conductor.ng">admin@conductor.ng</a>
                </p>
              </div>

              <h3 className="text-xl font-medium mb-3 mt-6">
                Account termination
              </h3>

              <div className="space-y-4">
                <p>
                  <strong>2.15.</strong> You may delete your account at any
                  time. In some cases, we will be unable to terminate your
                  account or may retain certain information for legitimate
                  purposes, such as to prevent fraud and ensure the safety of
                  our users, comply with legal obligations, or manage any
                  unresolved claims or disputes.
                </p>

                <p>
                  <strong>2.16.</strong> Accounts that have been inactive for
                  over 3 years may be deleted. We have the right to terminate or
                  suspend access to your account.
                </p>
              </div>
            </section>

            <Separator className="my-8" />

            <section>
              <h2 className="text-2xl font-semibold mb-4">3. Your safety</h2>

              <div className="space-y-4">
                <p>
                  <strong>3.1.</strong> The health and safety of Conductor.ng
                  Users is our priority. We take reasonable steps to keep the
                  Platform a safe and secure environment for our Users. For
                  example, we review and obtain documents of all drivers before
                  allowing them to provide their services. Additionally, we may
                  conduct spot checks to verify that the Driver&apos;s account
                  is used by the Driver who registered it, and that the Driver
                  uses the vehicle associated with this Driver&apos;s account.
                  We may ask Passengers to pass a liveness check or verify their
                  identity by providing a government issued ID number.
                </p>

                <p>
                  <strong>3.2.</strong> Despite our best efforts, we acknowledge
                  the limits of an online platform&apos;s ability to facilitate
                  offline safety. We have no control over the quality or safety
                  of the transportation that occurs as a result of the Services.
                  You acknowledge and accept the same.
                </p>

                <p>
                  <strong>3.3.</strong> Passengers are advised to review the
                  photos of the driver they see on the Platform to make sure it
                  is the same individual in person. If you notice that the
                  driver who arrived to you is different from the Driver details
                  stated in the Conductor.ng app, please refrain from using the
                  Service from such Driver and report to Conductor.ng and we
                  will investigate and apply liability measures to such driver.
                </p>

                <p>
                  <strong>3.4.</strong> We urge you to exercise caution and care
                  when interacting with other users. You avail and provide
                  services at your own risk.
                </p>

                <p>
                  <strong>3.5.</strong> In case of any suspected threat to
                  health or safety, immediately report it to user support
                  <a href="mailto:admin@conductor.ng">admin@conductor.ng</a>
                </p>

                <p>
                  <strong>3.6.</strong> We try to do our best to keep our app
                  safe and convenient for you. Therefore, we are constantly
                  improving and modifying user verification systems and the
                  functionality of our application.
                </p>
              </div>
            </section>

            <Separator className="my-8" />

            <section>
              <h2 className="text-2xl font-semibold mb-4">
                4. Users Obligations
              </h2>

              <div className="space-y-4">
                <p>
                  <strong>4.1.</strong> While using the Platform, You shall not:
                </p>
                <ol className="list-decimal ml-6 space-y-1">
                  <li>Violate any provision of this agreement;</li>
                  <li>
                    Violate any applicable law, court order, or government
                    regulation;
                  </li>
                  <li>
                    Provide any false personal information, or any information,
                    content, or material on account of a third- party without
                    permission
                  </li>
                  <li>
                    Attempt to access our Platform except as expressly permitted
                    by this agreement, or attempt to interfere with, damage,
                    disrupt, or impede the operation of the Platform and its
                    services and systems in any way;
                  </li>
                  <li>
                    Use the Platform in a way that is illegal, fraudulent,
                    defamatory, abusive, harassing, threatening, or obscene, or
                    violates the rights of any third-party;
                  </li>
                  <li>
                    Reverse engineer, disassemble, decompile, copy, clone,
                    modify, distribute or commercially exploit in any way the
                    Platform or any portion thereof;
                  </li>
                  <li>
                    Transmit or facilitate the transmission of any malware,
                    viruses, Trojan horses, or other program of a harmful or
                    destructive nature;
                  </li>
                  <li>
                    You shall not smoke, drink or carry any contraband
                    substances in the Vehicles or misbehave with any User or
                    distract the Driver or act in violation of Applicable Law.
                  </li>
                </ol>

                <p>
                  <strong>Compliance with rules and regulations-</strong> You
                  shall not use the Platform in a manner that exceeds the rights
                  granted for Your use as provided under this Agreement. You
                  agree that You will comply with all applicable laws, our
                  policies, procedures, and instructions as published on our
                  Platform or made available to You from time to time.
                </p>
                <p>
                  In addition to the obligations under Clause 4.1 above, By
                  providing the Services as a Driver, You represent, warrant,
                  and agree that:
                </p>

                <ol className="list-[upper-alpha] ml-6 space-y-1">
                  <li>
                    You possess a valid driver’s license and all other required
                    permissions and authorizations to provide the Services, You
                    are medically and legally fit to provide the Services;
                  </li>
                  <li>
                    u own, or have the legal right to operate, the vehicle You
                    use to provide the Services; such vehicle is in good
                    operating condition and meets the statutory and industry
                    safety standards and requirements;
                  </li>
                  <li>
                    You will only provide the Services using the vehicle that
                    has been approved by Conductor.ng;
                  </li>
                  <li>
                    You will not provide the Services while under the influence
                    of fatigue, alcohol or drugs, or otherwise engage in unsafe
                    or illegal behaviour while providing the Services;
                  </li>
                  <li>You will not discriminate against Passengers;</li>
                  <li>
                    You will not request any additional payment from the
                    Passengers via the Platform, other than tolls, state entry
                    tax, parking fees or other similar additional charges you
                    have paid to complete the ride;
                  </li>
                  <li>
                    You will comply with our reasonable requests to provide
                    information in connection with the Services and Your use of
                    the Platform;
                  </li>
                  <li>
                    You shall not use information You obtained via the Platform
                    for any purpose not related to the use or provision of
                    Driver&apos;s services, or for any purpose not agreed upon;
                  </li>
                  <li>
                    You comply with the requirements of all applicable laws
                    related to anti-money laundering, sanctions,
                    anti-corruption, anti-bribery, countering illegal trade and
                    countering terrorist financing, prohibiting the use of child
                    or forced labour, proper and not to take any action that may
                    lead to a violation of such laws, not to facilitate,
                    encourage or induce anyone to participate in such
                    activities.
                  </li>
                  <li>
                    You will comply with laws and policies applicable in
                    Nigeria.
                  </li>
                  <li>
                    You will provide the Service as per the terms agreed between
                    You and the Passenger in accordance with this Agreement and
                    applicable laws.
                  </li>
                </ol>
              </div>
            </section>

            <Separator className="my-8" />

            <section>
              <h2 className="text-2xl font-semibold mb-4">
                5. Driver and Passenger Communications
              </h2>

              <div className="space-y-4">
                <p>
                  <strong>5.1.</strong> You shall treat other Conductor.ng Users
                  with respect and you can only communicate with other users for
                  the purposes related to the provision/availing of services.
                  You shall not share any unnecessary contact information or
                  private customer information. Communication should end when
                  the Service is complete, unless it is to return a lost item.
                  Any other communication may be seen as harassment and may lead
                  to suspension or termination of your account with us.
                </p>
                <p>
                  <strong>5.2.</strong>You shall ensure that no communication
                  shall be inappropriate, profane, defamatory, infringing,
                  obscene, indecent or unlawful topic, blasphemous,
                  pornographic, libellous, invasive of another&apos;s privacy,
                  hateful, or racially, ethnically objectionable, disparaging,
                  relating or encouraging money laundering, or otherwise in any
                  manner unlawful.
                </p>
                <p>
                  <strong>5.3.</strong>We enable Users to communicate on the
                  Platform, for example, via comments, in-app chat or in-app
                  calls (availability of these features depends on your
                  location). We have the right to monitor and record your
                  communications with other users on the Platform to review
                  compliance with this Agreement.
                </p>
                <p>
                  <strong>5.4.</strong>Where this functionality is available,
                  you may contact the other user via their mobile number
                  provided in the app interface. In this case, mobile charges
                  set by your mobile carrier will apply.
                </p>
                <p>
                  <strong>5.5.</strong>You shall not use the information
                  received by you while providing/availing Services in any
                  manner which is unlawful, harassing, thought provoking and/or
                  offensive.
                </p>
              </div>
            </section>

            <Separator className="my-8" />

            <section>
              <h2 className="text-2xl font-semibold mb-4">
                6. Conductor.ng Communications
              </h2>

              <div className="space-y-4">
                <p>
                  <strong>6.1.</strong> We may send you operational
                  notifications about your account or Services which you have
                  provided/availed, updates about Conductor.ng and the Platform,
                  requests for feedback, and marketing communications. We may
                  contact you via e-mail, SMS, phone, and push notification. For
                  the types of communications that require your consent, we will
                  observe local laws on data protection with applicable options
                  to opt-out of this service.
                </p>
              </div>
            </section>

            <Separator className="my-8" />

            <section>
              <h2 className="text-2xl font-semibold mb-4">
                7. What you can&apos;t do on the Platform
              </h2>

              <div className="space-y-4">
                <p>
                  <strong>7.1.</strong>
                  You must not use the Platform to:
                </p>

                <ul className="list-disc ml-6 space-y-1">
                  <li>
                    do anything illegal and/or offensive to generally accepted
                    public standards;
                  </li>
                  <li>
                    {" "}
                    do anything that violates the terms under this Agreement or
                    any other Platform rules and Conductor.ng Policies;
                  </li>
                  <li>
                    use Platform for any purpose not intended by these terms
                    under this Agreement;
                  </li>
                  <li>
                    transfer or sell Your account, password or identification to
                    any other party;
                  </li>
                  <li>
                    impersonate another person or disguise Your identity, use or
                    attempt to use another user&apos;s account;
                  </li>
                  <li>
                    solicit others to engage in illegal or dangerous activities;
                  </li>
                  <li>stalk, threaten, or harass others;</li>
                  <li>
                    upload any content on the Platform which is inaccurate,
                    inappropriate, infringes anyone&apos;s rights (such as
                    intellectual property, privacy or personality rights) or is
                    otherwise illegal;
                  </li>
                  <li>
                    undermine the Platform&apos;s operations or security,
                    attempt to gain unauthorised access to the Platform or its
                    related systems or networks;
                  </li>
                  <li>extract any data or content from the Platform;</li>
                  <li>
                    create liability for Conductor.ng or cause us to become
                    subject to regulation as a transportation carrier or
                    provider of taxi service.
                  </li>
                </ul>
              </div>
            </section>

            <Separator className="my-8" />

            <section>
              <h2 className="text-2xl font-semibold mb-4">Zero Tolerance</h2>

              <div className="space-y-4">
                <p>
                  Conductor.ng expects Users to comply with all relevant laws,
                  rules and regulations when it comes to availing and providing
                  Services using the Platform. Discrimination of any kind is not
                  tolerated by the Users.
                </p>

                <p>
                  This includes refusing to provide/avail Services to/from users
                  based on characteristics protected under the laws of the
                  Federal republic of Nigeria. These characteristics include,
                  but are not limited to:
                </p>

                <ul className="list-disc ml-6 space-y-1">
                  <li>Race</li>
                  <li>Colour</li>
                  <li>Religion</li>
                  <li>National Origin</li>
                  <li>Age</li>
                  <li>Gender</li>
                  <li>Sexual Orientation</li>
                  <li>Gender Presentation</li>
                  <li>Pregnancy</li>
                  <li>Citizenship</li>
                  <li>Disability</li>
                </ul>

                <p>
                  Conductor.ng has a zero-tolerance policy towards
                  discrimination and unlawful conduct of any kind. In case of
                  receiving a complaint from a user about such behaviour that
                  violates the rules specified in the section Conductor.ng
                  reserves the right to take appropriate action against the
                  offender up to blocking the User&apos;s access to the account
                  registered on the Platform.
                </p>

                <p>
                  If you are denied service due to any of the factors mentioned
                  above, please let us know by email at (company mail).
                </p>
              </div>
            </section>

            <Separator className="my-8" />

            <section>
              <h2 className="text-2xl font-semibold mb-4">
                8. Conductor.ng&apos;s rights
              </h2>
              <div className="space-y-4">
                <p>
                  <strong>8.1.</strong> We have the right to investigate any
                  suspected breach of the terms of this Agreement. While we do
                  so, we are allowed to suspend your access to some or all the
                  features of the Platform, acting reasonably and objectively
                  depending on the seriousness of the suspected breach.
                </p>
                <p>
                  <strong>8.2.</strong> We, subsequently, might determine to
                  temporarily or permanently suspend or terminate Your account,
                  or impose limits on, or restrict Your access to features of
                  the Platform if:
                </p>
                <ul className="list-disc ml-6 space-y-1">
                  <li>
                    we determine, acting reasonably and objectively, that You
                    are in material or repeated breach of this Agreement or
                    other Conductor.ng rules and policies;
                  </li>
                  <li>
                    we have objective grounds to reasonably believe that You are
                    about to seriously breach the terms under this Agreement;
                  </li>
                  <li>we are legally required to do so;</li>
                  <li>
                    it is reasonably required in response to dealing with a
                    serious technical, safety or security issue.
                  </li>
                </ul>
                <p>
                  <strong>8.3.</strong> If we have previously terminated Your
                  account for breach of this Agreement, You are not permitted to
                  use our Platform again by registering with a different
                  number/email address. However, if You use our Platform again
                  (for example, by opening another account), we are entitled to
                  suspend or terminate any such accounts, at our sole
                  discretion.
                </p>
                <p>
                  <strong>8.4.</strong> If You think we have made a mistake in
                  suspending or terminating Your account, You can appeal through
                  (Company’s mail)
                </p>
              </div>
            </section>

            <Separator className="my-8" />

            <section>
              <h2 className="text-2xl font-semibold mb-4">9. Your Content</h2>
              <div className="space-y-4">
                <p>
                  <strong>9.1.</strong> You are responsible for the information,
                  files and images (collectively, “Content”) that You make
                  available on the Platform. You must ensure that Your Content
                  does not violate laws or anyone&apos;s rights. We do not
                  undertake to review the users&apos; Content and do not assume
                  any responsibility for it. We may remove or restrict access to
                  any Content, if we reasonably believe it is in breach of the
                  terms under this Agreement, or it causes harm to Conductor.ng,
                  our users or other third parties.
                </p>
                <p>
                  <strong>9.2.</strong> We do not own Your Content. By making
                  Content available on the Platform You grant Conductor.ng a
                  perpetual, irrevocable, worldwide, royalty-free, and
                  non-exclusive license to use Your Content, including to
                  reproduce, adapt or make derivative works, perform and
                  communicate Your Content to the public, for the purposes of
                  operating, developing and providing the Platform.
                </p>
              </div>
            </section>

            <Separator className="my-8" />

            <section>
              <h2 className="text-2xl font-semibold mb-4">
                10. Intellectual Property
              </h2>
              <div className="space-y-4">
                <p>
                  <strong>10.1.</strong> The Platform contains content (such as
                  design, images, sounds, texts, databases, computer codes,
                  registered and unregistered trademarks and other similar
                  objects) owned or licensed by Conductor.ng, which is protected
                  by copyright, trademark, patent, trade secret, and other
                  processes. Conductor.ng and its licensee, where applicable,
                  own all rights, title, and interest, including all related
                  intellectual property rights, in and to the Platform (software
                  and/or the app and by extension, the service and any
                  suggestions, ideas, enhancement requests, feedback,
                  recommendations or other information provided by you or any
                  other party relating to the Platform).
                </p>
                <p>
                  <strong>10.2.</strong> Conductor.ng grants You a limited,
                  non-exclusive, non-transferrable, non-assignable, revocable
                  license to: (a) access and use the Platform on your personal
                  device only for the purpose of using the Platform; and (b)
                  access and view any Content or materials that may be made
                  available through the Platform, in each case only for Your
                  personal, non-commercial use. All rights not expressly granted
                  to You herein are reserved by Conductor.ng and/ or
                  Conductor.ng’s licensee.
                </p>
                <p>
                  <strong>10.3.</strong> Conductor.ng does not grant to You any
                  license, express or implied, to the Intellectual Property of
                  Conductor.ng. For the purpose of this Agreement Intellectual
                  Property shall be defined as “Intellectual Property” - means
                  all of the following owned by Conductor.ng (a) filed,
                  registered and unregistered trademarks, service marks, trade
                  names, logos and goodwill associated therewith; (b) patents,
                  patentable inventions, computer programs, source code and
                  software; (c) databases; (d) trade secrets; (e) copyrights in
                  all works, including software programs; and (f) domain
                  names(g) marks, source code, object code, data, works,
                  including but not limited to look & feel, layouts,
                  information, text, data, music, video, images, scripts,
                  designs, graphics, button icons, instructions, and
                  illustrations. Conductor.ng will own and retain all rights,
                  title, and interest in and to the Platform and related
                  Intellectual Property (except for any third-party Intellectual
                  Property included therein, which shall be owned by such
                  third-party), including all data (including any usage data and
                  compilations thereof), information and software related
                  thereto. You are not permitted to use our Intellectual
                  Property without our express consent. You agree not to copy,
                  redistribute, modify, disassemble, reverse engineer,
                  decompile, publish, create derivative works or otherwise
                  exploit any Intellectual Property in violation of the
                  Intellectual Property rights of Conductor.ng or any other
                  third-party.
                </p>
                <p>
                  <strong>10.4.</strong> You may not, and may not allow any
                  other person to: (a) modify, reproduce, create derivative
                  works based on the Platform; (b) reverse engineer, decompile,
                  disassemble, or otherwise attempt to discover or change the
                  source code of the Platform to build a competitive product or
                  service, build a product using similar ideas, features,
                  functions, or graphics, copy any ideas, features, functions or
                  graphics; (c) frame, link to or mirror any part of the
                  Platform on any other server or wireless or internet-based
                  device; (d) post, distribute or reproduce in any way any
                  copyrighted material, trademarks, or other proprietary
                  information without obtaining the prior consent of
                  Conductor.ng.
                </p>
              </div>
            </section>

            <Separator className="my-8" />

            <section>
              <h2 className="text-2xl font-semibold mb-4">
                11. Personal Data Protection
              </h2>
              <div className="space-y-4">
                <p>
                  <strong>11.1.</strong> You agree and consent to Conductor.ng
                  using and processing Your personal data for the purposes and
                  in the manner as identified hereunder.
                </p>
                <p>
                  <strong>11.2.</strong> For the purposes of this Agreement,
                  “Personal Data” means information about You, from which You
                  are identifiable, including but not limited to Your name,
                  identification card number, address, telephone number, gender,
                  date of birth, email address, any information about You which
                  You have provided to Conductor.ng in registration forms,
                  application forms or any other similar forms and/or any
                  information about you that has been or may be collected,
                  stored, used and processed by Conductor.ng from time to time
                  and includes sensitive personal data, or as defined under
                  applicable law.
                </p>
                <p>
                  <strong>11.3.</strong> The provision of Your Personal Data is
                  voluntary. However, if You do not provide Conductor.ng with
                  Your Personal Data, Your access to the Platform may be
                  incomplete and Conductor.ng will not be able to process Your
                  Personal Data for the Purposes outlined below and may cause
                  Conductor.ng to be unable to allow You to use the Platform and
                  the Service.
                </p>
                <p>
                  <strong>11.4.</strong> You agree that Conductor.ng may send
                  You push notifications and e-mails, contact You by telephone
                  or text messages (including by an automatic telephone dialing
                  system) at any of the phone numbers provided by You or on Your
                  behalf in connection with a Conductor.ng account, including
                  for marketing purposes. You understand that You are not
                  required to provide this consent as a condition of purchasing
                  any property, goods or services.
                </p>
              </div>
            </section>

            <Separator className="my-8" />

            <section>
              <h2 className="text-2xl font-semibold mb-4">
                12. License Grant and Restrictions
              </h2>
              <div className="space-y-4">
                <p>
                  <strong>12.1. License.</strong> Subject to Your compliance
                  with the terms under this Agreement, Conductor.ng grants You a
                  restricted, non-exclusive, non-transferrable, non-assignable,
                  revocable license to: (a) access and use the Platform on Your
                  personal device only with the purpose to use the Platform to
                  avail/provide Services; and (b) access and view any content or
                  materials that may be made available through the Services, in
                  each case only for Your personal, non-commercial use. All
                  rights not expressly granted to you herein are reserved by
                  Conductor.ng and Conductor.ng&apos;s licensors.
                </p>
                <p>
                  <strong>12.2. Limitations and restrictions.</strong> You are
                  not allowed to: (a) remove any copyright, trademark or other
                  proprietary notices from any part of the Services; (b) modify,
                  create derivative works based upon, reproduce, distribute,
                  license, lease, sell, resell, transfer, publicly display,
                  stream, broadcast or otherwise use the Services unless given a
                  written consent to do so by Conductor.ng; (c) reverse
                  engineer, decompile, disassemble or otherwise attempt to
                  discover or change the source code of the Platform except as
                  may be permitted by applicable law; (d) frame, link to or
                  mirror any part of the Platform ; (e) cause or run any
                  programs or scripts for the purpose of scraping, indexing,
                  surveying or conducting any other form of data collecting on
                  any part of the Services or intentionally overloading or
                  hindering the operation and/or functionality of any aspect of
                  the Services and/or Platform ; or (f) try to gain unauthorized
                  access to or attempt to damage any part of the Platform or its
                  related systems or networks.
                </p>
                <p>
                  <strong>12.3.</strong> You shall not (i) license, sublicense,
                  sell, resell, transfer, assign, distribute or otherwise
                  commercially exploit or make available to any third party the
                  Platform and/or the software associated with the Platform
                  (“Software”) in any way; (ii) modify or make derivative works
                  based on the Platform and/or the Software; (iii) create
                  internet “links” to the Platform or “frame” or “mirror” any
                  Software on any other server or wireless or internet-based
                  device; (iv) reverse engineer or access the Platform and/or
                  Software in order to (a) build a competitive product or
                  service, (b) build a product using similar ideas, features,
                  functions or graphics of the Platform and/or the Software, or
                  (c) copy any ideas, features, functions or graphics of the
                  Platform and/or the Software, (v) launch an automated program
                  or script, including, but not limited to, web spiders, web
                  crawlers, web robots, web ants, web indexers, bots, viruses or
                  worms, or any program which may make multiple server requests
                  per second, or unduly burdens or hinders the operation and/or
                  performance of the Platform and/or the Software, (vi) use any
                  robot, spider, site search/retrieval application, or other
                  manual or automatic device or process to retrieve, index,
                  “data mine”, or in any way reproduce or circumvent the
                  navigational structure or presentation of the Platform or its
                  contents; (vii) post, distribute or reproduce in any way any
                  copyrighted material, trademarks, or other proprietary
                  information without obtaining the prior consent of the owner
                  of such proprietary rights, (viii) remove any copyright,
                  trademark or other proprietary rights notices contained in the
                  Platform.
                </p>
                <p>
                  <strong>12.4.</strong> You may use the Software and/or the
                  Platform only for Your personal purpose and shall not use the
                  Platform to: (i) send spam or otherwise duplicative or
                  unsolicited messages; (ii) send or store infringing, obscene,
                  threatening, libellous, or otherwise unlawful or tortious
                  material, including but not limited to materials harmful to
                  children or violative of third party privacy rights; (iii)
                  send material containing software viruses, worms, trojan
                  horses or other harmful computer code, files, scripts, agents
                  or programs; (iv) interfere with or disrupt the integrity or
                  performance of the Software and/or the Platform or the data
                  contained therein; (v) attempt to gain unauthorized access to
                  the Software and/or the Platform or its related systems or
                  networks; or (vi) impersonate any person or entity or
                  otherwise misrepresent your affiliation with a person or
                  entity. You should abstain from any conduct that could
                  possibly damage indrive&apos;s reputation or amount of being
                  disreputable.
                </p>
              </div>
            </section>

            <Separator className="my-8" />

            <section>
              <h2 className="text-2xl font-semibold mb-4">13. Indemnity</h2>
              <div className="space-y-4">
                <p>
                  <strong>13.1.</strong> You agree to defend, indemnify and hold
                  Conductor.ng and its affiliates, subsidiaries and their
                  officers, directors, employees and agents harmless from any
                  and all claims, demands, losses, liabilities, and expenses
                  (including reasonable attorneys&apos; fees) arising out of or
                  in connection with: (a) Your use and/or misuse of the Platform
                  or the Services; (b) Your breach or violation of any law
                  and/or any of the terms under this Agreement, any applicable
                  law or regulation, or the rights of any third party; (c) The
                  actions or inactions leading to any third party claims against
                  Conductor.ng (collectively, “Losses”).
                </p>
              </div>
            </section>

            <Separator className="my-8" />

            <section>
              <h2 className="text-2xl font-semibold mb-4">14. Liability</h2>
              <div className="space-y-4">
                <h3 className="text-xl font-medium mb-3">
                  Conductor.ng&apos;s liability
                </h3>
                <p>
                  <strong>14.1.</strong> Conductor.ng shall not be liable for
                  your missing ride/events or delays etc., as the Service is
                  dependent on many factors beyond the control of Conductor.ng.
                  You must schedule/book your ride after taking into account the
                  check-in time, traffic and weather conditions, political
                  rallies, natural calamities, traffic barricades, car
                  breakdowns and other unexpected delays.
                </p>
                <p>
                  <strong>14.2.</strong> Conductor.ng shall not be liable for
                  any damages resulting from the use of or inability to use the
                  Platform, including damages caused by wrong usage of the
                  Platform.
                </p>
                <p>
                  <strong>14.3.</strong> Conductor.ng shall not be liable for
                  any damages, liability or losses arising out: (i) Your use of
                  or reliance on the Service ; or (ii) any transaction or
                  relationship between Driver and Passenger
                </p>
                <p>
                  <strong>14.4.</strong> You shall take full responsibility of
                  Your items and luggage. In case of lost items inside the
                  vehicle during the journey, Conductor.ng will try to locate
                  the items on a “best-effort” basis but is not responsible for
                  the same in case of loss or damage to the same. If You leave
                  any goods in the vehicle or have any complaint in respect of
                  the Services or the use of the vehicle, You shall inform us of
                  the same immediately.
                </p>
                <p>
                  <strong>14.5.</strong> Without limiting the application of any
                  laws and regulations all conditions, representations, and
                  warranties, whether express, implied, statutory, or otherwise,
                  including, without limitation, any implied warranty of
                  merchantability, fitness for a particular purpose, or
                  noninfringement of third-party rights, are hereby excluded and
                  disclaimed to the highest and maximum extent.
                </p>
                <p>
                  <strong>14.6.</strong> To the maximum extent permitted by law,
                  in no event shall Conductor.ng be liable to You or anyone for
                  any direct, indirect, punitive, economic, future special,
                  exemplary, incidental, consequential, or other damages or
                  losses of any type or kind (including but not limited to
                  personal injury, emotional distress and loss of data, goods,
                  revenue, profits, use or other economic advantage), whether
                  arising in contract, tort (including negligence) or otherwise
                  arising out of, or in any way connected with the Platform,
                  including but not limited to the use or inability to use them,
                  any reliance placed by you on the completeness, accuracy or
                  existence of any advertising, or as a result of any
                  relationship or transaction between you and any Driver even if
                  Conductor.ng has been previously advised of the possibility of
                  such damages.
                </p>
                <p>
                  <strong>14.7. Disclaimer:</strong>
                  <br />
                  You agree that Conductor.ng is merely an electronic platform
                  to facilitate aggregation of Vehicles and does not in any
                  manner provide transportation services. Conductor.ng does not
                  endorse, advertise, advise or recommend You to avail the
                  Services of any Driver. Conductor.ng also does not guarantee
                  or provide assurance in respect of the behaviour, actions or
                  data of the Users posted on the Platform.
                  <br />
                  All images, audio, video and text in the Platform are only for
                  illustrative purposes. None of the models, actors or products
                  in the images, if any is endorsing the Services in any manner.
                  Any resemblance of any matter to anybody or anything is purely
                  unintentional and/or coincidental.
                </p>
              </div>
            </section>

            <Separator className="my-8" />

            <section>
              <h2 className="text-2xl font-semibold mb-4">
                15. Resolving disputes
              </h2>
              <div className="space-y-4">
                <h3 className="text-xl font-medium mb-3">
                  Governing law and arbitration
                </h3>
                <p>
                  <strong>15.1.</strong> This Agreement is governed by the law
                  of Nigeria. If we have a dispute, we will first try to resolve
                  it with You amicably, in accordance with applicable law. All
                  disputes or claims arising out of or in connection with these
                  Agreement, including disputes relating to its validity,
                  breach, termination or nullity, shall be finally referred to
                  and settled for arbitration under the Arbitration and
                  Mediation Act, 2023 to be adjudicated by a sole arbitrator to
                  be appointed by us. Arbitration shall be held in Lagos,
                  Nigeria, the proceedings of arbitration shall be held in
                  English. The arbitrators award shall be final and binding.
                </p>
                <p>
                  <strong>15.2.</strong> All disputes shall be settled within
                  one month by way of mutual understanding or by a grievance
                  officer as appointed by us.
                </p>
                <p>
                  <strong>15.3.</strong> In addition the above remedies,
                  Conductor.ng shall be entitled to an interim injunction,
                  restraining order or other equitable relief that a court of
                  competent jurisdiction may deem necessary or appropriate to
                  restrain any User from committing any violation of the law or
                  any covenant and obligations set under this Agreement. These
                  remedies are in addition to any other rights that we may have
                  at law or in equity.
                </p>
              </div>
            </section>

            <Separator className="my-8" />

            <section>
              <h2 className="text-2xl font-semibold mb-4">
                16. Changes to these Terms or the Platform
              </h2>
              <div className="space-y-4">
                <p>
                  <strong>16.1.</strong> We may make changes to this Agreement
                  or the Platform from time to time. When we update the terms
                  under this Agreement, we will post their latest version in our
                  app and our website.
                </p>
                <p>
                  <strong>16.2.</strong> If You would like to keep using the
                  Platform after we introduce changes to this Agreement or the
                  Platform, You will need to agree to the changes by continuing
                  to use our Platform. If You do not agree to such changes, You
                  will have to stop using the Platform.
                </p>
                <p>
                  <strong>16.3.</strong> Unless material changes are made to the
                  arbitration provisions, You agree that modification of these
                  Terms does not create a renewed opportunity to opt out of
                  arbitration (if applicable).
                </p>
              </div>
            </section>

            <Separator className="my-8" />

            <section>
              <h2 className="text-2xl font-semibold mb-4">17. General</h2>
              <div className="space-y-4">
                <p>
                  <strong>17.1.</strong> We promise to provide the Platform to
                  You with reasonable skill and care. Note, however, that we
                  provide the Platform “as available” or “as is”. It means that
                  we make no implied representation, warranty, or guarantee as
                  to the reliability, security, timeliness, quality,
                  suitability, availability, accuracy or completeness of the
                  Platform.
                </p>
                <p>
                  <strong>17.2.</strong> Please keep the Platform updated to its
                  current app version and ensure compatibility of Your device.
                  We advise You to use the Platform with a data plan with
                  unlimited or very high data usage limits.
                </p>
                <p>
                  <strong>17.3.</strong> The Platform may contain links to third
                  party websites, advertisements, services, offers or other
                  events or activities that are not provided, owned or
                  controlled by Conductor.ng. You use them at your own risk.
                </p>
                <p>
                  <strong>17.4.</strong> Nothing in these Terms affects any
                  statutory rights that you cannot contractually agree to alter
                  or give up. You will always have the full protections of the
                  laws that apply to You.
                </p>
                <p>
                  <strong>17.5. Force Majeure.</strong> Conductor.ng shall not
                  be liable to You or any other party if we are delayed or
                  unable to fulfill our obligations under this Agreement or
                  under any applicable law due to any abnormal and unpredictable
                  events beyond our control, including but not limited to Acts
                  of God, strikes, labor disputes, war, terrorism, equipment
                  breakdown, internet connection unavailability and the like, if
                  the respective consequences of such events could not have been
                  avoided despite all of our efforts or if we are bound by other
                  legal obligations.
                </p>
                <p>
                  <strong>17.6. Severability.</strong> If any provision
                  contained in this Agreement is determined to be invalid,
                  illegal, or unenforceable in any respect under any applicable
                  law, then such provision will be severed and replaced with a
                  new provision that most closely reflects the original
                  intention of the parties, and the remaining provisions of this
                  Agreement will remain in full force and effect.
                </p>
                <p>
                  <strong>17.7. Waiver.</strong> Failure by Conductor.ng to
                  exercise or enforce any provision of this Agreement shall not
                  be deemed to be a waiver of future enforcement of those or any
                  other rights under this Agreement.
                </p>
                <p>
                  <strong>17.8. Construction.</strong> Section headings are for
                  convenience only.
                </p>
                <p>
                  <strong>17.9.</strong> You shall not assign Your rights under
                  this Agreement without prior written approval of Conductor.ng.
                  Conductor.ng can assign its rights under this Agreement
                  without any prior written consent or notice.
                </p>
              </div>
            </section>

            <Separator className="my-8" />

            <section>
              <h2 className="text-2xl font-semibold mb-4">
                Contacting Conductor.ng
              </h2>

              <div className="space-y-2">
                <p>
                  <strong>Contact</strong>
                </p>
                <p>
                  Address: &nbsp;No 7 Ahmadu Bello Close Peace Court Est
                  Lokogoma Abuja
                </p>
                <p>
                  Email: &nbsp;
                  <a href="mailto:admin@conductor.ng">admin@conductor.ng</a>
                </p>
                <p>Phone: &nbsp;+2348106902386</p>
              </div>
            </section>

            <div className="text-center mt-12 pt-8 border-t border-border">
              <p className="text-sm text-muted-foreground">
                Last updated: {new Date().toLocaleDateString()}
              </p>
            </div>
          </div>
        </div>
      </div>
      <section className="bg-[#0a0704]">
        <div className="md:px-0 px-[24px]">
          <Footer />
        </div>
      </section>
    </div>
  );
};

export default TermsOfUse;
